### ISSUE TITLE
作为代理访问https网站时，会出现以下错误。

### ISSUE THREAD

**Issue by GrootPank** [5alt/tornado-proxy#1]
WARNING:tornado.general:SSL Error on 15 ('58.215.111.12', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
这个警告之后，页面无法显示。http请求一切正常。

错误发生在更新python2 和 一些依赖库包括dev之后。

debug分析：
 s = ssl.wrap_socket(socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0))
 upstream = tornado.iostream.SSLIOStream(s,)
 upstream.connect((host, int(port)), start_tunnel, host)
在连接host后进行了ssl验证，验证失败后关闭了连接。 尚未找到解决方法，求助楼主。
（个人认为 是 底层代码的更新导致了问题出现）

**Comment by 5alt** [comment]
这个问题应该是在访问有证书错误的网站时会触发，就是在浏览器里直接访问会提示证书错误那样。我也看了下报错，处理逻辑在底层的tornado库里。我找找办法看看能不能解决吧，估计在不改底层库的情况下会比较困难。

感谢提交 issue ~

**Comment by GrootPank** [comment]
Hi 5alt，浏览器访问是没有提示证书错误。 是所有https网站都会出现 以上报错，这个发生在将tornado等一些依赖库升级后。如果楼主能复现就好了。
